services:
  db:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - POSTGRES_USER=trueplace
      - POSTGRES_PASSWORD=trueplace
      - POSTGRES_DB=trueplace
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trueplace -d trueplace || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    image: ghcr.io/mecolejr/trueplace-backend:latest
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://trueplace:trueplace@db:5432/trueplace?schema=public
      - NODE_ENV=production
      - CORS_ORIGIN=http://localhost:5178
      - DEV_AUTH=false
      - CACHE_TTL_MS=600000
    ports:
      - '4000:4000'
  frontend:
    image: ghcr.io/mecolejr/trueplace-frontend:latest
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - '5178:80'
volumes:
  db_data:
